config/routes.rb
BackChannelApp::Application.routes.draw do

  root :to => "login#login"
  get "posts/search_post_show"
  post "posts/destroy"
  get "login/show"

  get "posts/search_for_post"
  post "posts/search_post_show"
  post "comments/edit"

  get "users/save_new_user"

  get "users/post_user_save"
  post "users/destroy"

  get "posts/generate_report"
  post "posts/generate_report"
  get "posts/report"
  post "posts/report"
  post "comments/destroy"
  post "post_votes/destroy"
  post "post_votes/create"

  post "comment_votes/destroy"
  post "comment_votes/create"
  post "posts/search_for_post"
   post "users/update"

  post "login/user"
  get "login/user"

  post "login/admin"
  get "login/admin"

  get "login/login"
  post "login/login"
  post "login/logout"
  post "login/index"
  get "login/logout"

  get 'user/show'

  get 'posts/index'
  post 'posts/index'
post 'posts/edit'
  get 'login/index'

  get 'comments/new'
  post 'comments/new'
  post 'posts/new'

 get 'posts/show'

  resources :tags

  resources :comment_votes

  resources :post_votes

  resources :comments

  resources :categories

  resources :posts

  resources :users

  root :to => 'login#login'

end

app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  attr_accessible :comment_id, :post_id, :user_id

  belongs_to :comment
  belongs_to :post
  belongs_to :user

  #validates_presence_of :comment_id
  #validates_presence_of :user_id
  #validates_uniqueness_of :comment_id, :scope => :user_id

end

app/controllers/comment_votes_controller.rb
class CommentVotesController < ApplicationController
  # GET /comment_votes
  # GET /comment_votes.json
  before_filter :authorize
  def index
    @comment_votes = CommentVote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comment_votes }
    end
  end

  # GET /comment_votes/1
  # GET /comment_votes/1.json
  def show
    @comment_vote = CommentVote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment_vote }
    end
  end

  # GET /comment_votes/new
  # GET /comment_votes/new.json
  def new
    @comment_vote = CommentVote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment_vote }
    end
  end

  # GET /comment_votes/1/edit
  def edit
    @comment_vote = CommentVote.find(params[:id])
  end

  # POST /comment_votes
  # POST /comment_votes.json
  def create
     if ( !params[:post_id].nil? and !params[:user_id].nil? and !params[:comment_id].nil?)
    @comment_vote = CommentVote.new(:user_id => params[:user_id], :post_id => params[:post_id], :comment_id => params[:comment_id])
     else
       @comment_vote = CommentVote.new(params[:comment_vote])
      end
    if !params[:post_id].nil?
    @post = Post.find(params[:post_id])



    respond_to do |format|
      if @comment_vote.save
        format.html { redirect_to @post, notice: 'Successfully voted.' }
        format.json { render json: @post, status: :created, location: @post }
        format.js
      else
        format.html { redirect_to @post, notice: 'You cannot vote twice' }
        format.json { render json: @post, status: :created, location: @post }
        format.js
        end
    end

    else
      respond_to do |format|
        if @comment_vote.save
          format.html { redirect_to @comment_vote, notice: 'Comment vote was successfully created.' }
          format.json { render json: @comment_vote, status: :created, location: @comment_vote }
        else
          format.html { render action: "new" }
          format.json { render json: @comment_vote.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /comment_votes/1
  # PUT /comment_votes/1.json
  def update
    @comment_vote = CommentVote.find(params[:id])

    respond_to do |format|
      if @comment_vote.update_attributes(params[:comment_vote])
        format.html { redirect_to @comment_vote, notice: 'Comment vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comment_votes/1
  # DELETE /comment_votes/1.json
  def destroy
    if ( !params[:post_id].nil? and !params[:user_id].nil? and !params[:comment_id].nil?)
    @comment_vote = CommentVote.find_by_post_id_and_user_id_and_comment_id(params[:post_id],params[:user_id],params[:comment_id])
    else
      @comment_vote = CommentVote.find(params[:id])
    end
    @comment_vote.destroy
    if !params[:post_id].nil?

    @post = Post.find(params[:post_id])

    respond_to do |format|
      format.html { redirect_to @post, notice: 'Successfully unvoted.' }
      format.json { head :no_content }
    end
    else
      respond_to do |format|
        format.html { redirect_to comment_votes_url }
        format.json { head :no_content }
      end

    end
  end


  end

app/helpers/comment_votes_helper.rb
module CommentVotesHelper
end

app/views/comment_votes/_form.html.erb
<%= form_for(@comment_vote) do |f| %>
  <% if @comment_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment_vote.errors.count, "error") %> prohibited this comment_vote from being saved:</h2>

      <ul>
      <% @comment_vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comment_votes/edit.html.erb
<h1>Editing comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment_vote %> |
<%= link_to 'Back', comment_votes_path %>

app/views/comment_votes/index.html.erb
<h1>Listing comment_votes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comment_votes.each do |comment_vote| %>
  <tr>
    <td><%= link_to 'Show', comment_vote %></td>
    <td><%= link_to 'Edit', edit_comment_vote_path(comment_vote) %></td>
    <td><%= link_to 'Destroy', comment_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment vote', new_comment_vote_path %>

app/views/comment_votes/new.html.erb
<h1>New comment_vote</h1>

<%= render 'form' %>

<%= link_to 'Back', comment_votes_path %>

app/views/comment_votes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_vote_path(@comment_vote) %> |
<%= link_to 'Back', comment_votes_path %>